#!/bin/bash

mkdir COAP
cd COAP
mkdir myCoAP
cd myCoAP
git clone https://github.com/eclipse/californium.git
sudo apt-get update
sudo apt-get upgrade 
sudo apt-get install maven
sudo apt-get install pi4j
update-java-alternatives -l

