#!/bin/bash

mkdir COAP
cd COAP
mkdir myCoAP
cd myCoAP
git clone https://github.com/eclipse/californium.git
sudo apt-get update
sudo apt-get upgrade 
sudo apt-get install maven
curl -s get.pi4j.com | sudo bash
update-java-alternatives -l

