#!/bin/bash

cd /etc/wpa_supplicant
rm wpa_supplicant.conf
echo "
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
        ssid="eduroam"
        scan_ssid=1
        proto=RSN
        key_mgmt=WPA-EAP
        eap=PEAP
        pairwise=CCMP
        phase1="peaplabel=0"
        phase2="auth=MSCHAPV2"
        anonymous_identity="anonymous@vt.edu"

        identity="pid@vt.edu"
        password="password"
}
" >> wpa_supplicant.conf
sudo reboot